version: "3"
services:
  app:
    # replace username/repo:tag with your name and image details
    image: runetvilum/survey_app:v1
    environment:
      API: 192.168.255.37
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - postgres
      - tiles
  tiles:
    # replace username/repo:tag with your name and image details
    image: klokantech/tileserver-gl
    ports:
      - "8080:80"
    volumes:
      - "./tiles:/data"
    networks:
      - webnet
  db:
    # replace username/repo:tag with your name and image details
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    networks:
      - webnet
networks:
  webnet: