version: "3"
services:
  app:
    image: runetvilum/web-gis-app
    environment:
      URL_PREFIX: http://localhost:3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - "/Users/runetvilum/develop/GitHub/web-gis-app/mbtiles:/mbtiles"
      - "/Users/runetvilum/develop/GitHub/web-gis-app/styles:/styles"
      - "/Users/runetvilum/develop/GitHub/web-gis-app/fonts:/fonts"
      - "/Users/runetvilum/develop/GitHub/web-gis-app/xfm:/xfm"
    networks:
      - webnet
  feathers:
    image: ruunetvilum/web-gis-feathers
    ports:
      - "3030:3030"
    volumes:
      - "/Users/runetvilum/develop/GitHub/web-gis-app/mbtiles:/mbtiles"
    networks:
      - webnet
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: Zxcv1234
      POSTGRES_DB: survey
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    networks:
      - webnet
networks:
  webnet: