version: "3"
services:
  tiles:
    # replace username/repo:tag with your name and image details
    image: klokantech/tileserver-gl
    ports:
      - "8080:80"
    volumes:
      - "./tiles:/data"
    networks:
      - webnet
  db:
    # replace username/repo:tag with your name and image details
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    networks:
      - webnet
networks:
  webnet: